### ISSUE TITLE
[no 36] | Spaces in URIs

### ISSUE THREAD

**Issue by ovann86** [AGLDWG/TR#9]
[no 36] | Spaces in URIs are ***NOT RECOMMENDED***. | ***NOT RECOMMENDED***
-- | -- | --

I'm wondering if spaces in URI's should be allowed at all.

The URI scheme will become harder to predict where some people have and some people haven't used spaces. Additionally, people may use another character instead of a space.

I'm also thinking about how spaces can be presented as their encoded form of %20 - which would reduce the readability of the URI.

I would rather spaces being not allowed and nominating a specific character (e.g. a dash -) for separating multiple words in a URL component.

**Comment by nicholascar** [comment]
Hi @ovann86, I appreciate you looking in to and considering aspects of the Guidelines. Looking at your GitHub account I can't recall if we've met! Can you please drop me a not on <nicholas.car@csiro.au> so I can know your interest in the Guidelines better?

Are you aware that we are about to issue a major overhaul of the Guidelines due to a new base URI (`linked.data.gov.au`) and new patterns? See the [Guidelines v2](https://github.com/AGLDWG/TR/blob/master/guidelines/URI-Guidelines-v2.md) draft.

**Comment by nicholascar** [comment]
New Guidelines issued at <https://github.com/AGLDWG/guidelines> and note that spaces are not allowed in the new patterning.
